name: build and test

on:
    push:
    pull_request: 
        branches: [ main ]
        paths: 
        - '**.cs'
        - '**.csproj'

env:
    DOTNET_VERSION: '8.0.404'        

jobs:
    build-and-test:
        
        name: build-and-test-${{matrix.os}}
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest]
    
        services:
          sqlserver:
            image: mcr.microsoft.com/mssql/server:2019-latest
            ports:
              - 1433:1433
            env:
              ACCEPT_EULA: Y
              MSSQL_SA_PASSWORD: PkjRej8@30
            volumes:
              - data:/var/opt/mssql    

        steps:
        - uses: actions/checkout@v4
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
    
        - name: Install dependencies
          run: dotnet restore
          working-directory: ./src

        - name: Wait for SQL Server to be ready
          run: |
            until /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P PkjRej8@30 -Q "SELECT 1"; do
              echo "Waiting for SQL Server to start..."
              sleep 5
            done

        - name: Apply Migrations
          run: dotnet ef database update --project src/Contatos.Web.Infrastructure.Data/Contatos.Web.Infrastructure.Data.csproj
          
        - name: Build
          run: dotnet build --configuration Release --no-restore
          working-directory: ./src
        
        - name: Test
          run: dotnet test --no-restore --verbosity normal
          working-directory: ./src