name: build and test

on:
    push:
    pull_request: 
        branches: [ main ]
        paths: 
        - '**.cs'
        - '**.csproj'

env:
    DOTNET_VERSION: '8.0.404'        

jobs:
    build-and-test:
        
        name: build-and-test-${{matrix.os}}
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest]  

        services:
          sqlserver:
            image: mcr.microsoft.com/mssql/server:2022-latest
            volumes:
              - sql_data:/var/opt/mssql
            options: --memory=4g
            ports:
              - 1434:1433
            env:
              ACCEPT_EULA: "Y"
              SA_PASSWORD: "PkjRej8@30"

        steps:
        - uses: actions/checkout@v4
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
    
        - name: Install dependencies
          run: dotnet restore
          working-directory: ./src

        - name: Wait for SQL Server to be ready
          run: |
            echo "Waiting for SQL Server to be fully operational..."
            until /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P PkjRej8@30 -Q "SELECT @@VERSION" > /dev/null 2>&1
            do
            echo "SQL Server is still initializing. Waiting..."
            sleep 5
            done
            echo "SQL Server is now operational."

        - name: Initialize SQL Server
          run: |
            /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P PkjRej8@30 -i ./scripts/init-db.sql

        - name: Apply Migrations
          run: dotnet ef database update --project src/Contatos.Web.Infrastructure.Data/Contatos.Web.Infrastructure.Data.csproj
          
        - name: Build
          run: dotnet build --configuration Release --no-restore
          working-directory: ./src
        
        - name: Test
          run: dotnet test --no-restore --verbosity normal
          working-directory: ./src