name: CI Pipeline

on:
    push:
    pull_request: 
        branches: [ main ]
        paths: 
        - '**.cs'
        - '**.csproj'
env:
    DOTNET_VERSION: "8.x"       

jobs:
    build-and-test:
        
        name: build-and-test-${{matrix.os}}
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest]  

        services:
          sqlserver:
            image: mcr.microsoft.com/mssql/server:2022-latest
            volumes:
              - sql_data:/var/opt/mssql
            options: >-
                --memory=4g
                --health-cmd "exit 0"
                --health-interval 10s
                --health-timeout 5s
                --health-retries 3   
            ports:
              - 1434:1433
            env:
              ACCEPT_EULA: "Y"
              SA_PASSWORD: "PkjRej8@30"             

        steps:
        - uses: actions/checkout@v4
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
    
        - name: Install EF Core CLI Tools
          run: dotnet tool install --global dotnet-ef
    
        - name: Add .NET tools to PATH
          run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

        - name: Install dependencies
          run: dotnet restore
          working-directory: ./src
          
        - name: Build
          run: dotnet build --configuration Release --no-restore
          working-directory: ./src    
          
        - name: Run Migrations
          env:
            ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ContatosDB;User=sa;Password=PkjRej8@30"
          run: dotnet ef database update          

        - name: Run Unit and Integration Tests
          env: 
            ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ContatosDB;User=sa;Password=PkjRej8@30"
          run: dotnet test ./src/Contatos.Web.Test/Contatos.Web.Tests.csproj --configuration Release --no-build --logger trx --verbosity normal

