name: build and test

on:
    push:
    pull_request: 
        branches: [ main ]
        paths: 
        - '**.cs'
        - '**.csproj'

env:
    DOTNET_VERSION: '8.0.404'        

jobs:
    build-and-test:
        
        name: build-and-test-${{matrix.os}}
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest]  

        services:
          sqlserver:
            image: mcr.microsoft.com/mssql/server:2022-latest
            volumes:
              - sql_data:/var/opt/mssql
            options: --memory=4g
            ports:
              - 1434:1433
            env:
              ACCEPT_EULA: "Y"
              SA_PASSWORD: "PkjRej8@30"

        steps:
        - uses: actions/checkout@v4
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
    
        - name: Install dependencies
          run: dotnet restore
          working-directory: ./src
          
        - name: Build
          run: dotnet build --configuration Release --no-restore
          working-directory: ./src       

        - name: Run Unit and Integration Tests
          run: dotnet test ./src/Contatos.Web.Test/Contatos.Web.Tests.csproj --configuration Release --no-build --logger trx --verbosity normal

